//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpfunDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod admin_set_creator;
pub mod admin_set_idl_authority;
pub mod admin_update_token_incentives;
pub mod buy;
pub mod buy_exact_sol_in;
pub mod claim_token_incentives;
pub mod close_user_volume_accumulator;
pub mod collect_creator_fee;
pub mod cpi_event;
pub mod create;
pub mod create_v2;
pub mod extend_account;
pub mod init_user_volume_accumulator;
pub mod initialize;
pub mod migrate;
pub mod sell;
pub mod set_creator;
pub mod set_mayhem_virtual_params;
pub mod set_metaplex_creator;
pub mod set_params;
pub mod set_reserved_fee_recipients;
pub mod sync_user_volume_accumulator;
pub mod toggle_create_v2;
pub mod toggle_mayhem_mode;
pub mod update_global_authority;

pub use self::{
    admin_set_creator::*, admin_set_idl_authority::*, admin_update_token_incentives::*, buy::*,
    buy_exact_sol_in::*, claim_token_incentives::*, close_user_volume_accumulator::*,
    collect_creator_fee::*, cpi_event::*, create::*, create_v2::*, extend_account::*,
    init_user_volume_accumulator::*, initialize::*, migrate::*, sell::*, set_creator::*,
    set_mayhem_virtual_params::*, set_metaplex_creator::*, set_params::*,
    set_reserved_fee_recipients::*, sync_user_volume_accumulator::*, toggle_create_v2::*,
    toggle_mayhem_mode::*, update_global_authority::*,
};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpfunInstruction {
    AdminSetCreator(AdminSetCreator),
    AdminSetIdlAuthority(AdminSetIdlAuthority),
    AdminUpdateTokenIncentives(AdminUpdateTokenIncentives),
    Buy(Buy),
    BuyExactSolIn(BuyExactSolIn),
    ClaimTokenIncentives(ClaimTokenIncentives),
    CloseUserVolumeAccumulator(CloseUserVolumeAccumulator),
    CollectCreatorFee(CollectCreatorFee),
    Create(Create),
    CreateV2(CreateV2),
    ExtendAccount(ExtendAccount),
    Initialize(Initialize),
    InitUserVolumeAccumulator(InitUserVolumeAccumulator),
    Migrate(Migrate),
    Sell(Sell),
    SetCreator(SetCreator),
    SetMayhemVirtualParams(SetMayhemVirtualParams),
    SetMetaplexCreator(SetMetaplexCreator),
    SetParams(SetParams),
    SetReservedFeeRecipients(SetReservedFeeRecipients),
    SyncUserVolumeAccumulator(SyncUserVolumeAccumulator),
    ToggleCreateV2(ToggleCreateV2),
    ToggleMayhemMode(ToggleMayhemMode),
    UpdateGlobalAuthority(UpdateGlobalAuthority),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpfunDecoder {
    type InstructionType = PumpfunInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        #[cfg(feature = "minimal-events")]
        {
            if data.len() < 8 {
                return None;
            }
            let disc = <[u8; 8]>::try_from(&data[..8]).ok()?;
            return match disc {
                [24, 30, 200, 40, 5, 28, 7, 119] => create::Create::decode(data).map(|decoded| {
                    carbon_core::instruction::DecodedInstruction {
                        program_id: instruction.program_id,
                        data: PumpfunInstruction::Create(decoded),
                        accounts: instruction.accounts.clone(),
                    }
                }),
                [214, 144, 76, 236, 95, 139, 49, 180] => {
                    create_v2::CreateV2::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CreateV2(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [155, 234, 231, 146, 236, 158, 162, 30] => {
                    migrate::Migrate::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::Migrate(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [228, 69, 165, 46, 81, 203, 154, 29] => {
                    cpi_event::CpiEvent::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CpiEvent(Box::new(decoded)),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                _ => None,
            };
        }

        #[cfg(not(feature = "minimal-events"))]
        {
            if data.len() < 8 {
                return None;
            }
            let disc = <[u8; 8]>::try_from(&data[..8]).ok()?;
            return match disc {
                [69, 25, 171, 142, 57, 239, 13, 4] => {
                    admin_set_creator::AdminSetCreator::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::AdminSetCreator(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [8, 217, 96, 231, 144, 104, 192, 5] => {
                    admin_set_idl_authority::AdminSetIdlAuthority::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::AdminSetIdlAuthority(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [209, 11, 115, 87, 213, 23, 124, 204] => {
                    admin_update_token_incentives::AdminUpdateTokenIncentives::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::AdminUpdateTokenIncentives(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [102, 6, 61, 18, 1, 218, 235, 234] => buy::Buy::decode(data).map(|decoded| {
                    carbon_core::instruction::DecodedInstruction {
                        program_id: instruction.program_id,
                        data: PumpfunInstruction::Buy(decoded),
                        accounts: instruction.accounts.clone(),
                    }
                }),
                [56, 252, 116, 8, 158, 223, 205, 95] => {
                    buy_exact_sol_in::BuyExactSolIn::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::BuyExactSolIn(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [16, 4, 71, 28, 204, 1, 40, 27] => {
                    claim_token_incentives::ClaimTokenIncentives::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::ClaimTokenIncentives(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [249, 69, 164, 218, 150, 103, 84, 138] => {
                    close_user_volume_accumulator::CloseUserVolumeAccumulator::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CloseUserVolumeAccumulator(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [20, 22, 86, 123, 198, 28, 219, 132] => {
                    collect_creator_fee::CollectCreatorFee::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CollectCreatorFee(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [228, 69, 165, 46, 81, 203, 154, 29] => {
                    cpi_event::CpiEvent::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CpiEvent(Box::new(decoded)),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [24, 30, 200, 40, 5, 28, 7, 119] => create::Create::decode(data).map(
                    |decoded| carbon_core::instruction::DecodedInstruction {
                        program_id: instruction.program_id,
                        data: PumpfunInstruction::Create(decoded),
                        accounts: instruction.accounts.clone(),
                    },
                ),
                [214, 144, 76, 236, 95, 139, 49, 180] => {
                    create_v2::CreateV2::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::CreateV2(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [234, 102, 194, 203, 150, 72, 62, 229] => {
                    extend_account::ExtendAccount::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::ExtendAccount(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [94, 6, 202, 115, 255, 96, 232, 183] => {
                    init_user_volume_accumulator::InitUserVolumeAccumulator::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::InitUserVolumeAccumulator(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [175, 175, 109, 31, 13, 152, 155, 237] => {
                    initialize::Initialize::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::Initialize(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [155, 234, 231, 146, 236, 158, 162, 30] => {
                    migrate::Migrate::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::Migrate(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [51, 230, 133, 164, 1, 127, 131, 173] => sell::Sell::decode(data).map(
                    |decoded| carbon_core::instruction::DecodedInstruction {
                        program_id: instruction.program_id,
                        data: PumpfunInstruction::Sell(decoded),
                        accounts: instruction.accounts.clone(),
                    },
                ),
                [254, 148, 255, 112, 207, 142, 170, 165] => {
                    set_creator::SetCreator::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SetCreator(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [61, 169, 188, 191, 153, 149, 42, 97] => {
                    set_mayhem_virtual_params::SetMayhemVirtualParams::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SetMayhemVirtualParams(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [138, 96, 174, 217, 48, 85, 197, 246] => {
                    set_metaplex_creator::SetMetaplexCreator::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SetMetaplexCreator(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [27, 234, 178, 52, 147, 2, 187, 141] => {
                    set_params::SetParams::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SetParams(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [111, 172, 162, 232, 114, 89, 213, 142] => {
                    set_reserved_fee_recipients::SetReservedFeeRecipients::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SetReservedFeeRecipients(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [86, 31, 192, 87, 163, 87, 79, 238] => {
                    sync_user_volume_accumulator::SyncUserVolumeAccumulator::decode(data).map(
                        |decoded| carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::SyncUserVolumeAccumulator(decoded),
                            accounts: instruction.accounts.clone(),
                        },
                    )
                }
                [28, 255, 230, 240, 172, 107, 203, 171] => {
                    toggle_create_v2::ToggleCreateV2::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::ToggleCreateV2(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [1, 9, 111, 208, 100, 31, 255, 163] => {
                    toggle_mayhem_mode::ToggleMayhemMode::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::ToggleMayhemMode(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                [227, 181, 74, 196, 208, 21, 97, 213] => {
                    update_global_authority::UpdateGlobalAuthority::decode(data).map(|decoded| {
                        carbon_core::instruction::DecodedInstruction {
                            program_id: instruction.program_id,
                            data: PumpfunInstruction::UpdateGlobalAuthority(decoded),
                            accounts: instruction.accounts.clone(),
                        }
                    })
                }
                _ => None,
            };
        }
    }
}
